// import { Inter } from 'next/font/google'
// import './globals.css'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function SettingsLayout({ children }) {
  return (
    <section className="settings">
      {children}
    </section>
  )
}
