"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Image from 'next/image'
import Link from 'next/link';
import { usePathname } from 'next/navigation'





const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  const pathname = usePathname()
  console.log(pathname);

  return (
    <html lang="en">
      <body className={inter.className}>

        <div className='container'>
          {children}
        </div>

        <footer>

          <div className="footer-div">

            <Link href={`/`}>

              <div className={`footer-div-inner ${(pathname == "/") && "active"}`}>
                <Image
                  src={"/assests/home.png"}
                  width={25}
                  height={25}
                  alt='home'
                />

                <p className="footer-pgh">
                  Home
                </p>
              </div>
            </Link>

            <Link href={`/activity`}>

              <div className={`footer-div-inner ${(pathname == "/activity") && "active"}`}>
                <Image
                  src={"/assests/compass.png"}
                  width={25}
                  height={25}
                  alt='compass'
                />

                <p className="footer-pgh">
                  Activity
                </p>
              </div>
            </Link>

            <Link href={`/history`}>

              <div className={`footer-div-inner ${(pathname == "/history") && "active"}`}>
                <Image
                  src={"/assests/list.png"}
                  width={25}
                  height={25}
                  alt='History'
                />

                <p className="footer-pgh">
                  History
                </p>
              </div>
            </Link>

            <Link href={`/settings`}>

              <div className={`footer-div-inner ${(pathname == "/settings") && "active"} ${(pathname == "/settings/editprofile") && "active"}`}>
                <Image
                  src={"/assests/settings.png"}
                  width={25}
                  height={25}
                  alt='Settings'
                />

                <p className="footer-pgh">
                  Settings
                </p>
              </div>
            </Link>

          </div>

        </footer>

      </body>
    </html>
  );
}
